import sqlite3
con = sqlite3.connect("bot.db")
cur = con.cursor()
# cur.execute("DROP TABLE pay")
# cur.execute("DROP TABLE users")
# cur.execute("DROP TABLE btn")
cur.execute("DROP TABLE grand")
# cur.execute("DROP TABLE drivers")
# cur.execute("DROP TABLE driver_score")
cur.execute("CREATE TABLE IF NOT EXISTS users(id,lang,lastd,join_time,sub_count,score,fantasy,protection,validity)")
cur.execute("CREATE TABLE IF NOT EXISTS pay(user_id,pay_id,order_id,type)")
cur.execute("CREATE TABLE IF NOT EXISTS btn(tag,text)")
cur.execute("CREATE TABLE IF NOT EXISTS drivers(for_grand,name,driver_id,avg,avg_plus,avg_count)")
cur.execute("CREATE TABLE IF NOT EXISTS grand(num, name, close, state)")
cur.execute("CREATE TABLE IF NOT EXISTS driver_score(user_id,driver_id,for_grand)")
cur.execute("CREATE TABLE IF NOT EXISTS invite(user_id,invite_id)")
cur.execute("CREATE TABLE IF NOT EXISTS admins(_id)")